ar_tags:
  - id: 1
    position: [0.0, 0.0, 0.0]
  - id: 14
    position: [1.2, 0.0, 0.0]
  - id: 5
    position: [1.8, 0.6, 0.0]
  - id: 13
    position: [0.6, 1.2, 0.0]
  - id: 27
    position: [0.0, 1.8, 0.0]
  - id: 25
    position: [1.2, 1.8, 0.0]
  - id: 6
    position: [2.4, 1.8, 0.0]
  - id: 4
    position: [0.6, 2.4, 0.0]
  - id: 20
    position: [1.8, 3.0, 0.0]
  - id: 17
    position: [0.0, 3.6, 0.0]
  - id: 33
    position: [1.2, 3.6, 0.0]
  - id: 23
    position: [2.4, 4.2, 0.0]
  - id: 22
    position: [0.0, 4.8, 0.0]
  - id: 21
    position: [1.2, 4.8, 0.0]
  - id: 10
    position: [2.4, 5.4, 0.0]
  - id: 18
    position: [0.6, 6.0, 0.0]
  - id: 24
    position: [1.8, 6.0, 0.0]
  - id: 26
    position: [1.2, 6.6, 0.0]
  - id: 12
    position: [2.4, 6.6, 0.0]
  - id: 19
    position: [0.0, 7.8, 0.0]
  - id: 9
    position: [1.8, 7.8, 0.0]

